### ISSUE TITLE
Once fixed, TLS 1.2 issue come back again after few weeks

### ISSUE THREAD

**Issue by mahmoudghorbelMG** [microsoft/azure-devops-tls12#12]
Hi all
After diagnosing the TLS 1.2 issue using the AzureDevOpsTls12Analysis.ps1 script on my Windows server 2016 (I have three VMs in Azure), the problem was fixed the first time with the generated mitigation scripts Mitigation-NetFramework.ps1 and Mitigation-RegFunctionsDEL.ps1 (run as administrator as suggested in the script output) and a restart was performed. The agent can connect again to azure devops and it shows the green online status. 
However, after few weeks, the agent appeared as offline in azure devops and the same problem was diagnosed. I reused the same script (AzureDevOpsTls12Analysis.ps1) with the mitigation script (only Mitigation-RegFunctionsDEL.ps1 was generated this time) to refix the issue. Of course, a restart was required.
Once again, the same issue reappeared 4 or 5 times since the first one last June. Somebody can help to fix this issue once and for all.
Best regards

**Comment by on-the-ray** [comment]
Are those computers in the Active Directory domain? This seems like AD group policy being applied on your computer from Domain Controller. If not this, there may be other mechanism which applies some policies regularly. 

To verify AAD/GPO hypothesis, you can call command "gpupdate /target:computer /force" after fixing most recent issue. If the issue reappears after GPUpdate, you have a proof that this is enforced by DC. 

The newest version of AzureDevOpsTls12Analysis.ps1 actually does this check for you and prints "Mitigation was not effective! Local cipher suite list is being overriden by group policies." if enforced.
