### ISSUE TITLE
Error - Mitigation script not created

### ISSUE THREAD

**Issue by codemau5** [microsoft/azure-devops-tls12#13]
This line:
    $filePathAbsolute = $fileName | Resolve-Path
causes error:
Resolve-Path : Cannot find path
'C:\...\azure-devops-tls12-main\azure-devops-tls12-main\Mitigation-RegFunctionsDEL.ps1' because it
does not exist.

and $filePathAbsolute is null,
followed by error:
Out-File : Cannot bind argument to parameter 'FilePath' because it is null.
At C:\...\azure-devops-tls12-main\azure-devops-tls12-main\AzureDevOpsTls12Analysis.ps1:133 char:33
+     $lines | Out-File -FilePath $filePathAbsolute -Force

Happened on Powershell version 7.3.0 and on version 5.1.22621.608

To mitigate I created an empty ps1 file to be written into

**Comment by on-the-ray** [comment]
Thanks! fixing...

**Comment by on-the-ray** [comment]
Fixed. 

 Apologize for inconvenience and thanks again for reporting this!
