### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by tonaltti** [microsoft/azure-devops-tls12#14]
Probing tests fails if proxy is required. Would be nice to have proxy support as command line parameter, for example `./AzureDevOpsTls12Analysis.ps1 -Proxy "myproxy:myport"`.

**Comment by on-the-ray** [comment]
If I get this right you have terminating proxy scenario: CLIENT -> PROXY (myproxy:myport) -> ADO.  In such case the tool is not intended to be run on the client. but on the machine hosting the PROXY. 

In the scenario, the PROXY exposes HTTPS port for communication with the set of cipher suites and version of TLS protocol of its choice (not neccessarilly same as the TLS protocol version and cipher suite set exposed by ADO). The script has list of ADO-enabled cipher suites enabled hardcoded. So, if the script was adjusted based on your ask and be run on the CLIENT, it would be giving potenially improper results (scanning for ADO-enabled cipher suites, while PROXY would have other set).
