### ISSUE TITLE
Agents offline and unable to connect during TLS deprecation

### ISSUE THREAD

**Issue by JHG-AndrewNugent** [microsoft/azure-devops-tls12#4]
Please note that we also have an MS Premier support case open on this issue and have been through numerous engineers and scenarios, all with no fix. 
Our situation is thus:
2012R2 servers (also some 2008 servers) with .Net 4.8. We've gone through the ciphers and they're supposed to be correct, however, we still have the issue.  We are rapidly approaching the deadline of Thursday and thus far, Premier support has been unable to provide a solution. Posting here in hopes that we can get some coordination between the ADO devs and Premier support to find a solution. Premier support case number available on request.

PS C:> (Invoke-WebRequest -Uri status.dev.azure.com).StatusDescription
Invoke-WebRequest : The underlying connection was closed: An unexpected error occurred on a send.
At line:1 char:2
+ (Invoke-WebRequest -Uri status.dev.azure.com).StatusDescription
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

Output of the recommended check script is:
```
Azure DevOps TLS 1.2 transition readiness checker v. 2022-03-24.1
==============================
| Probing Azure DevOps sites |
==============================
Probing: status.dev.azure.com
ISSUE FOUND: This may be TLS compatibility issue!
Probe failed when TLS-negotiating to 13.107.6.183:443. Error: Unable to read data from the transport connection: An exis
ting connection was forcibly closed by the remote host.
********************************************************************************
=========================================
| Analysis of TLS 1.2 compatibility: OS |
=========================================
PS Version: 5.1.14409.1005
PS Edition:  Desktop
Win Build Version:  6.3.9600.0
CLR Version:  4.0.30319.42000
Skipping Get-TlsCipherSuite due to version of OS lower than WS 2016
********************************************************************************
TLS 1.2 client usage enabled.
********************************************************************************
Allowed required cipher suites per local: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 TL
S_DHE_RSA_WITH_AES_256_GCM_SHA384 TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
Missing required cipher suites per local:
Allowed required cipher suites per GP: not defined
Disabled required cipher suites per GP:
At least one of the TLS 1.2 cipher suites required by Azure DevOps enabled on the machine (by registry check).
Enabled cipher suites: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 TLS_DHE_RSA_WITH_AES_
256_GCM_SHA384 TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
=====================================================
| Analysis of TLS 1.2 compatibility: .NET Framework |
=====================================================
.NET Framework release is 4.7+ (release 528049)
If you do not use legacy .NET applications you can ignore below warnings (if any detected). Always fix issues found in t
he above OS-based analysis first.
TLS 1.2 enforced for applications targetting .NET Framework 4.0/4.5.x
TLS 1.2 enforced for applications targetting .NET Framework 4.0/4.5.x (32bit app on 64bit OS)
TLS 1.2 enforced for applications targetting .NET Framework 3.5
TLS 1.2 enforced for applications targetting .NET Framework 3.5 (32bit app on 64bit OS)
```

**Comment by on-the-ray** [comment]
@JHG-AndrewNugent  pls rerun with the newest version of the script. It was made more compatible with WS2012 and lower. Based on that, I'm happy to have a look.

**Comment by on-the-ray** [comment]
Also, please rerun the script at PowerShell 7 to circumvent .NET Framework layer and see if the outputs are consistent.

Check if you have this Win update applied https://support.microsoft.com/kb/2919355

And list explicitly all the edits you have already done to registry (based on suggestions of previous runs of this script or others...)

**Comment by on-the-ray** [comment]
Great you provided capture of ClientHello packet, it is clear that cipher suites are the issue, so PS 7 not needed.

Out of four cipher suites honoured by AzDO, WS 2012 R2 is supposed to support two: TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384. 

What we can see from the script output, however, is that TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 are configured as enabled (which they obviously are not since ClientHello does not advertise them), and also TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,  TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 which W2k12 R2 should not suppot regardless of patches/updates. Looks like some discrepancy.

I suggest to try to override the local cipher suites using local group policy. 

Run GPEDIT.msc:
- Navigate to "Computer Config/Administrative Templates/Network/SSL Config Settings"
- Choose setting ""SSL Cipher Suite Order"" -> Edit
 - Set as 'Enabled'
- 'SSL Cipher Suites' should be pre-populated with comma-separated list of cipher suites. Make sure these two are there (or insert them): TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
- Press 'OK' button
Restart the computer

![image](https://user-images.githubusercontent.com/76961530/160903359-ff6f623f-3f59-4810-a252-526185dd41fd.png)

**Comment by JHG-AndrewNugent** [comment]
No joy, Had to pair the field down due to a 1023 char limit, but actually ended up seeing MORE ciphers in the script output. 
Unless I'm missing something?

```
PS C:\temp\> .\AzureDevOpsTls12Analysis.ps1
Azure DevOps TLS 1.2 transition readiness checker v. 2022-03-29
==============================
| Probing Azure DevOps sites |
==============================
Probing: status.dev.azure.com
ISSUE FOUND: This may be TLS compatibility issue!
Probe failed when TLS-negotiating to 13.107.6.183:443. Error: Unable to read data from the transport connection: An exis
ting connection was forcibly closed by the remote host.
********************************************************************************
=========================================
| Analysis of TLS 1.2 compatibility: OS |
=========================================
PS Version: 5.1.14409.1005
PS Edition:  Desktop
Win Build Version:  6.3.9600.0
CLR Version:  4.0.30319.42000
********************************************************************************
TLS 1.2 client usage enabled.
********************************************************************************
Running BCrypt check...
At least one of the TLS 1.2 cipher suites required by Azure DevOps enabled on the machine.
Matching cipher suites: TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
********************************************************************************
Running registry check...
Group Policy cipher suites override defined: TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 TLS
_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P256 TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384 TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
_P256 TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P384 TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA_P256 TLS_ECDHE_RSA_WITH_AES_256_CBC_
SHA_P384 TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA_P256 TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA_P384 TLS_DHE_RSA_WITH_AES_256_CBC_SH
A TLS_DHE_RSA_WITH_AES_128_CBC_SHA TLS_RSA_WITH_AES_256_GCM_SHA384 TLS_RSA_WITH_AES_128_GCM_SHA256 TLS_RSA_WITH_AES_256_
CBC_SHA256 TLS_RSA_WITH_AES_128_CBC_SHA256 TLS_RSA_WITH_AES_256_CBC_SHA TLS_RSA_WITH_AES_128_CBC_SHA TLS_ECDHE_ECDSA_WIT
H_AES_128_GCM_SHA256_P384 TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384_P384 TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256_P256 TLS_
ECDHE_ECDSA_WITH_AES_128_CBC_SHA256_P384 TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA_P256 TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA_
P384 SSL_CK_RC4_128_WITH_MD5 SSL_CK_DES_192_EDE3_CBC_WITH_MD5
Missing cipher suites:
No need to change the GP override since cipher suites required by Azure DevOps are already enabled.
=====================================================
| Analysis of TLS 1.2 compatibility: .NET Framework |
=====================================================
.NET Framework release is 4.7+ (release 528049)
If you do not use legacy .NET applications you can ignore below warnings (if any detected). Always fix issues found in t
he above OS-based analysis first.
TLS 1.2 enforced for applications targetting .NET Framework 4.0/4.5.x
TLS 1.2 enforced for applications targetting .NET Framework 4.0/4.5.x (32bit app on 64bit OS)
TLS 1.2 enforced for applications targetting .NET Framework 3.5
TLS 1.2 enforced for applications targetting .NET Framework 3.5 (32bit app on 64bit OS)
```

**Comment by on-the-ray** [comment]
What is outputed by the script matches what I'd expect should fix the situation (except that it did not). 

If you're sure that computer was restarted after performing this GP change, then no further ideas here. But I'm sure the MS Premier Support will help.

Please kindly update this issue when you get to solution for others in comunity.

**Comment by JHG-AndrewNugent** [comment]
Thanks for trying. Premier Support is going down the enable Diffie-Hellman path, we'll see where that goes and I'll update if we find a fix. 

Given we haven't been able to find a fix, what are our options for postponing full deprecation as scheduled for tomorrow?

**Comment by JHG-AndrewNugent** [comment]
Update, we think we have a fix. Turns out we had a quiet Domain level group policy that was explicitly disabling Diffie-Hellman. Once we unjoined the server from the domain and enabled DH, we were able to connect to status.dev.azure.com. 
If you're having similar issues, I highly recommend taking a very careful look at something like "gpresult /h c:\temp\gpresult.html"

**Comment by on-the-ray** [comment]
Cool, great catch!

So seems that this domain level GP was setting Enabled=0 at `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\KeyExchangeAlgorithms\Diffie-Hellman` and thus invalidating _DHE_ cipher suites although they were listed as enabled otherwise.

![image](https://user-images.githubusercontent.com/76961530/160935233-1b5c0b08-9d5d-4857-baf1-2e961e58bece.png)

If not sure what was there before, can you share what you have under that registry key now?

**Comment by JHG-AndrewNugent** [comment]
Yep, thats the one. Note that the value must be "ffffffff", and not simply "1":
![94289b75-21cc-4250-b8e6-2a2c9cde12f4](https://user-images.githubusercontent.com/73201248/160958386-4efdbe9d-b68c-448b-92c8-9c0a24d49ac9.jpg)

**Comment by on-the-ray** [comment]
The script has been extended to support this case.
