### ISSUE TITLE
SSL Cipher Suites maximum length in gpedit

### ISSUE THREAD

**Issue by promicroNL** [microsoft/azure-devops-tls12#6]
One of the mitigations stated to override the group policy (Computer Config/Administrative Templates/Network/SSL Config Settings).
![image](https://user-images.githubusercontent.com/77012051/167796786-75a92bf7-12b7-46b1-9543-e7a014c4952b.png)

The maximum length of this field (in Windows2012) is 1023 characters, in my case this resulted in an incomplete SSL Cipher Suite.

May I suggest to limit `$suggestedFunctionsContent` for the gpedit mitigation?

**Comment by on-the-ray** [comment]
Thanks for reporting this. 

It seems that this limitation was removed at some point. At my workstation (W11), the cipher suite string is longer than 1023 characters and also advisory string is different.
![image](https://user-images.githubusercontent.com/76961530/167935411-d815bb6d-ca0b-479d-b9aa-bfc439cd130f.png)

Automatic trimming would be a bit dangerous. It could silently trim cipher suites which the user needs (thus connectivity to other applications could get broken).

I suggest to use the OS pre-generated the list (which appears after Enabled is clicked) and only insert the needed cipher suites (if not present):
![image](https://user-images.githubusercontent.com/76961530/167940393-7eef7f95-b4c3-4aa1-974b-358e49a3f5b7.png)

**Comment by promicroNL** [comment]
Thanks @on-the-ray  
The limitation is on Windows Server 2008 (updated my original post) and despite all the fixes I can't seem connect to Azure DevOps. Officially this Windows version isn't even supported.
![image](https://user-images.githubusercontent.com/77012051/168000781-cd02294e-fbc4-4415-9a15-2a457d765ab9.png)

I'll ask IT for another, more recent ;-), server.

**Comment by on-the-ray** [comment]
@promicroNL 

WS 2008 R2 is TLS 1.2 compatible but specific updates need to be applied to support at least subset of the cipher suites which Azure DevOps requires (not sure if the same holds also for the older WS 2008 SP2).

Some relevant articles:
https://support.microsoft.com/help/4019276/update-to-add-support-for-tls-1-1-and-tls-1-2-in-windows-server-2008-s
https://support.microsoft.com/en-us/topic/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-winhttp-in-windows-c4bd73d2-31d7-761e-0178-11268bb10392
https://support.microsoft.com/en-us/topic/update-to-add-support-for-tls-1-1-and-tls-1-2-in-windows-server-2008-sp2-windows-embedded-posready-2009-and-windows-embedded-standard-2009-b6ab553a-fa8f-3f5e-287c-e752eb3ce5f4
