### ISSUE TITLE
When enabling Diffie-Hellman KeyExchangeAlgorithm, should also set ServerMinKeyBitLength to avoid logjam

### ISSUE THREAD

**Issue by matt961** [microsoft/azure-devops-tls12#8]
Per https://weakdh.org/ the ServerMinKeyBitLength on reg path `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\KeyExchangeAlgorithms\Diffie-Hellman` should be set to 2048 (`0x800`) when enabling Diffie-Hellman.

I discovered this workaround by this post https://developercommunity.visualstudio.com/t/azure-devops-agent-installed-on-windows-server-201/1651426#T-N1651596 . Adding this reg dword, the check script returns success and `testssl.sh --logjam` passes.

This mitigation is helpful for agents deployed to web servers where tighter security is required.

**Comment by on-the-ray** [comment]
@matt961 this makes perfect sense! Implemented.
