### ISSUE TITLE
ISSUE FOUND: This may be TLS compatibility issue! Probe failed when TLS-negotiating to 13.107.6.183:443. Error: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by AishWabtec** [microsoft/azure-devops-tls12#9]
Hi,

After executing the powershell script. I am getting below error :

Azure DevOps TLS 1.2 transition readiness checker v. 2022-06-16
==============================
| Probing Azure DevOps sites |
==============================
Probing: status.dev.azure.com
ISSUE FOUND: This may be TLS compatibility issue!
Probe failed when TLS-negotiating to 13.107.6.183:443. Error: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
********************************************************************************
=========================================
| Analysis of TLS 1.2 compatibility: OS |
=========================================
Getting environment info...
PS Version: 5.1.14409.1005
PS Edition:  Desktop
CLR Version:  4.0.30319.42000
OS Version: system.environment: 6.2.9200.0, systeminfo: 6.2.9200 --> 6.2.9200.0
********************************************************************************
Running Hot Fix check...
Checking KB3140245...
Hotfix KB3140245 found: \\TCOSVM-T0052\root\cimv2:Win32_QuickFixEngineering.HotFixID="KB3140245",ServicePackInEffect=""
Hotfix check passed.
********************************************************************************
For old Windows versions (WS 2012, Windows 7 and older) TLS 1.2 must be explicitly enabled...
TLS 1.2 client usage enabled.
********************************************************************************
Running Cipher Suite check (BCrypt)...
All enabled cipher suites: TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 TLS_RSA_WITH_AES_128_CBC_SHA256 TLS_RSA_WITH_AES_128_CBC_SHA TLS_RSA_WITH_AES_256_CBC_SHA256 TLS_RSA_WITH_AES_256_CBC_SHA TLS_RS
A_WITH_RC4_128_SHA TLS_RSA_WITH_3DES_EDE_CBC_SHA TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P256 TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P384 TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA_P256 TLS_ECDHE_RSA_WI
TH_AES_128_CBC_SHA_P384 TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA_P256 TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA_P384 TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256_P256 TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256_P2
56 TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384_P384 TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384_P384 TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA_P256 TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA_P384 TLS_ECDHE_ECDS
A_WITH_AES_256_CBC_SHA_P256 TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA_P384 TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 TLS_DHE_DSS_WITH_AES_128_CBC_SHA TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 TLS_DHE_DSS_WITH
_AES_256_CBC_SHA TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA TLS_RSA_WITH_RC4_128_MD5
At least one of the TLS 1.2 cipher suites supported by Azure DevOps is enabled and working.
Matching cipher suites: TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
********************************************************************************
Running Group Policy check...
Group Policy cipher suites override defined: TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 TLS_RSA_WITH_AES_128_CBC_SHA256 TLS_RSA_WITH_AES_128_CBC_SHA TLS_RSA_WITH_AES_256_CBC_SHA256 TLS_RSA_WITH_AES_
256_CBC_SHA TLS_RSA_WITH_RC4_128_SHA TLS_RSA_WITH_3DES_EDE_CBC_SHA TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P256 TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P384 TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA_P25
6 TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA_P384 TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA_P256 TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA_P384 TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256_P256 TLS_ECDHE_ECDSA_WITH_AES
_128_CBC_SHA256_P256 TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384_P384 TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384_P384 TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA_P256 TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA_P
384 TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA_P256 TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA_P384 TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 TLS_DHE_DSS_WITH_AES_128_CBC_SHA TLS_DHE_DSS_WITH_AES_256_CBC_SHA25
6 TLS_DHE_DSS_WITH_AES_256_CBC_SHA TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA TLS_RSA_WITH_RC4_128_MD5
Missing cipher suites: 
No need to change the GP override since cipher suites required by Azure DevOps are already enabled.
********************************************************************************
Running Key Exchange check...
Diffie-Hellman key exchange allowed.
Key Exchange check passed.
********************************************************************************
Running Elliptic Curve check...
Skipping elliptic curve check due to OS version.
=====================================================
| Analysis of TLS 1.2 compatibility: .NET Framework |
=====================================================
.NET Framework release is 4.7+ (release 528049)
TLS 1.2 enforced for applications targetting .NET Framework 4.0/4.5.x
TLS 1.2 enforced for applications targetting .NET Framework 4.0/4.5.x (32bit app on 64bit OS)
TLS 1.2 enforced for applications targetting .NET Framework 3.5
TLS 1.2 enforced for applications targetting .NET Framework 3.5 (32bit app on 64bit OS)
All mitigations required to ensure TLS 1.2-compatibility of legacy .NET applications are in place.

Please help me to fix this probe issue.

**Comment by on-the-ray** [comment]
What is the checker output if you remove group-policy override and restart the computer? 

Go to: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Cryptography\Configuration\Local\SSL\00010002
Rename property "Functions" to "Functions2" (this is just to make a backup of the previous value)
Restart the computer.
Go back to registry and chck if "Functions" still does not exist.
If "Functions" does not exist, run the script to find what it outputs.
Rename "Functions2" back to "Functions" and restart the computer to return to previous setup.

**Comment by on-the-ray** [comment]
Also, what is the network environment of the machine where you reproduce it? Is there some firewall along the way?

Can you please check following commands and get back to me what each of them outputs?

- (Invoke-WebRequest -Uri https://status.dev.azure.com -UseBasicParsing).StatusDescription
- (Invoke-WebRequest -Uri https://github.com -UseBasicParsing).StatusDescription
- (Invoke-WebRequest -Uri https://portal.azure.com -UseBasicParsing).StatusDescription
- (Invoke-WebRequest -Uri https://marketplace.visualstudio.com -UseBasicParsing).StatusDescription

**Comment by AishWabtec** [comment]
Hi All,

This issue got fixed after windows update. hence closing this ticket.

**Comment by on-the-ray** [comment]
@AishWabtec can you please clarify which windows updates were applied, i.e. which KB(s)? 

The checker script is supposed to recognize missing KBs. In your case the check passed ("Hotfix KB3140245 found..."), therefore the script probably should test more KBs for OS version 6.2.9200.

**Comment by AishWabtec** [comment]
I am not sure which windows update fix this issue because these vm's were not updated since 2020.
